# Generated by Django 4.2.4 on 2023-08-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'can_read_all_books')]},
        ),
    ]
