# Generated by Django 4.2.4 on 2023-08-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isReccomended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
