# Generated by Django 4.2.4 on 2023-09-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_isreccomended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isReccomended',
        ),
        migrations.RemoveField(
            model_name='book',
            name='url',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
