# Generated by Django 4.2.4 on 2023-09-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_bookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
